server:
  port: ${PORT}
spring:
  datasource:
    url: ${DATABASE_URL}
    username:  ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 500
          order_inserts: true
          order_updates: true
    show-sql: false
app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}